---
- hosts: localhost
  tasks:
    # Install Python (if not installed)
    - name: Ensure Python is installed
      become: yes
      apt:
        name: python3
        state: present

    # Ensure Git is installed (required for pulling code)
    - name: Ensure Git is installed
      become: yes
      apt:
        name: git
        state: present

    # Use a directory accessible to your current user
    - name: Ensure destination directory exists
      file:
        path: /home/{{ lookup('env', 'USER') }}/C270_Project
        state: directory
        mode: '0755'

    # Pull the latest changes from GitHub
    - name: Pull latest code from GitHub
      git:
        repo: https://github.com/23024801-Clement/C270_Project.git
        dest: /home/{{ lookup('env', 'USER') }}/C270_Project
        version: master

    # Run the Python script
    - name: Run Python app
      command: python3 app.py
      args:
        chdir: /home/{{ lookup('env', 'USER') }}/C270_Project
